SCP-4277 Contract ID management
input-output-hk/marlowe-cardano pull request #233
Opened 2022-08-25 20:53 UTC by jhbertra

Changes included:

- Adds a new `marlowe-history` server process which manages multiple follower threads and exposes a query API and a command API (as well as a temporary repl)
- Adds a new `marlowe-history-cli` which can be used to communicate with a `marlowe-history` server. supported commands:
  - `marlowe-history-cli add CONTRACT_ID` starts following a contract by its ID
  - `marlowe-history-cli rm CONTRACT_ID` stops following a contract by its ID
  - `marlowe-history-cli ls -[sf]` lists all followed contracts. `-s` shows the status of the follower and `-f` also shows failed contracts (e.g. if you use `add` and it fails to follow the contract, the failure message will be shown next to the contract ID with `-sf`)

2022-08-25 22:27 UTC, bwbush commented on marlowe-runtime/marlowe-history-cli/Main.hs
> +  exitFailure
This function is identical to `System.Exit.die` in `base`.

2022-08-25 22:28 UTC, bwbush commented on marlowe-runtime/marlowe-history-cli/Main.hs
> +      , O.help "The port number for issuing commands to the history server"
Should we list the default port numbers in the help strings?

2022-08-25 23:53 UTC, bwbush requested changes
Looks good, and `chainseekd`, `marlowe-history`, `marlowe-history-cli`, and `marlowe-follower` all seem to be working in concert for me on the `preview` network, where I tested them with contract `75601b84f1581da4d4c3f1ac3818cee89ce674f288ee152b24938555e982e0fe#1`.

One of the commands is missing help
```
cabal run exe:marlowe-history -- --help                                                                                                                                                                                     
Up to date
Invalid option `--help'

Usage: marlowe-history [--chain-seek-port-number PORT_NUMBER] 
                       [--chain-seek-query-port-number PORT_NUMBER] 
                       [-c|--command-port PORT_NUMBER] 
                       [-c|--query-port PORT_NUMBER] 
                       [--chain-seek-host HOST_NAME] [-h|--host HOST_NAME]

  Contract follower for Marlowe Runtime
```

I also noticed two `-p` options in `chainseekd`:
```
Usage: chainseekd [--version] (-s|--socket-path SOCKET_FILE) 
                  [-m|--testnet-magic INTEGER] [-d|--database-uri DATABASE_URI]
                  --genesis-config-file-hash CONFIG_HASH
                  --genesis-config-file CONFIG_FILE [-h|--host HOST_NAME] 
                  [-p|--port-number PORT_NUMBER] 
                  [-p|--query-port-number PORT_NUMBER]
```
The same problem happens for `-p` and -`c` in `marlowe-history` and `marlowe-history-cli` and `marlowe-follower`. We should probably review all of the CLIs and guard against the root cause.

2022-08-26 18:17 UTC, jhbertra commented
> We should probably review all of the CLIs and guard against the root cause.

The root cause being copy-pasting code? Not sure how we're going to guard against that in practice :stuck_out_tongue: I'm reviewing all the CLI options now

2022-08-26 19:27 UTC, bwbush approved these changes

2022-08-26 19:28 UTC, merged