Scp 4606/e2e ls
input-output-hk/marlowe-cardano pull request #354
Opened 2022-11-14 20:29 UTC by ladamesny

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

2022-11-22 07:22 UTC, bwbush commented on marlowe-runtime/integration-tests/ls/non_empty_history.sh
> +marlowe ls
One could capture the output of this command to a variable or file, and then compare it to the expected value, returning a success or failure code.

2022-11-22 07:22 UTC, bwbush commented on marlowe-runtime/integration-tests/ls/empty_history.sh
> +marlowe ls
One could capture the output of this command to a variable or file, and then compare it to the expected value, returning a success or failure code.

2022-11-22 07:22 UTC, bwbush requested changes
I think we could have this return error codes for success or failure. See comments.

2023-01-17 14:53 UTC, ladamesny commented
Closing this PR as jupyter notebooks is not the approach we want to take for our integration tests.

2023-01-17 14:53 UTC, closed without merging