Add halogen-store to marlowe-playground
input-output-hk/marlowe-cardano pull request #46
Opened 2022-01-04 16:53 UTC by paluh

2022-01-04 17:01 UTC, paluh commented
This is nearly a copy of @hrajchert change for `marlowe-run`.

It can seems strange that we provide `MonadAsk` instance for our `AppM` which exposes part of our mutable global state but that is a part of the [official `StoreT` API too](https://github.com/thomashoneyman/purescript-halogen-store/blob/v0.3.0/src/Halogen/Store/Monad.purs#L59). I'm still not sure about this approach and my first reaction was also [sceptical](https://github.com/input-output-hk/marlowe-cardano/pull/39#pullrequestreview-843788028) ...

2022-01-04 20:49 UTC, jhbertra requested changes
I agree with your PR comment, I think we still want to keep the `Env` and the `Store` separate via `ReaderT Env (StoreT Store Aff) a`

2022-01-04 20:49 UTC, jhbertra commented on marlowe-playground-client/src/Store.purs
> +data Action
For now, what do you think about the simple Action type proposed in `HalogenStore`?

```
type Action = Store -> Store
```

2022-01-04 20:49 UTC, jhbertra commented on marlowe-playground-client/src/Store.purs
> +newtype Env
I agree with your comment in the PR description - I don't think this is a good idea. I'm not a fan of putting the "read-only" environment in the state like this.  I propose we have `newtype AppM = AppM (ReaderT Env (StoreT Store Aff) a)` instead. That way, the immutable environment cannot be accidentally modified.

2022-01-10 12:00 UTC, paluh commented
As discussed earlier I'm closing this because I ended up with empty store.

2022-01-10 12:00 UTC, closed without merging