Fix `Second` parsing in the marlowe-cli
input-output-hk/marlowe-cardano pull request #576
Opened 2023-05-08 16:12 UTC by paluh

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
        - Review required
        - [ ] Substantial changes to code, test, or documentation
        - [ ] Change made to Marlowe validator (@bwbush and @palas must be included as reviewers)
        - Review not required
        - [ ] Minor changes to non-critical code, documentation, nix derivations, configuration files, or scripts
        - [ ] Formatting, spelling, grammar, or reorganization
    - [x] Reviewer requested

2023-05-08 16:43 UTC, bwbush approved these changes
Thanks. I now understand the source of the problem.

2023-05-08 18:34 UTC, jhbertra requested changes
This PR introduces a user-facing change (a bugfix), please include a changelog update

2023-05-09 07:02 UTC, paluh commented
@bwbush Bumped the "patch" version number (from 0.0.10.2 to 0.0.10.3) - is this proper change?

@jhbertra Added the bug fix changelog.

2023-05-10 13:35 UTC, jhbertra requested changes
Please don't update the version yet - this happens when we release

2023-05-10 13:36 UTC, jhbertra commented on marlowe-cli/marlowe-cli.cabal
> +version: 0.0.10.3
```suggestion
version: 0.0.10.2
```

2023-05-15 14:31 UTC, merged