PLT-6842 Autodeploy on push
input-output-hk/marlowe-cardano pull request #750
Opened 2023-11-14 07:42 UTC by tshaynik

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
    - [ ] Operables are updated with changes to executable command line options.
    - [ ] Deploy charts updated with changes to operables.
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
        - Review required
        - [ ] Substantial changes to code, test, or documentation
        - [ ] Change made to Marlowe validator (@bwbush and @palas must be included as reviewers)
        - Review not required
        - [ ] Minor changes to non-critical code, documentation, nix derivations, configuration files, or scripts
        - [ ] Formatting, spelling, grammar, or reorganization
    - [ ] Reviewer requested

2023-11-14 21:37 UTC, tshaynik commented
This is ready to review. It's still a draft just as a reminder to make a couple of changes before merging: only run on the `main` branch and to commit to `main`.

2023-11-15 11:24 UTC, shlevy commented
@tshaynik In other repos with this approach to CD, the image deployment is part of the vela deployment pipeline. Here it's not, do we have some way to wait for the GHA image deployment to finish before kicking off the vela deploy?

2023-11-16 21:55 UTC, shlevy approved these changes

2023-11-21 04:32 UTC, tshaynik commented
This should be ready to merge now.

2023-11-21 14:31 UTC, jhbertra commented on .github/workflows/deploy.yml
> +            yq e -i '.instances.demo.webTag = env(TAG)' deploy/marlowe-runtime/values.yaml
```suggestion
            yq e -i '.instances.demo.tag = env(TAG)' deploy/marlowe-runtime/values.yaml
            yq e -i '.instances.demo.webTag = env(TAG)' deploy/marlowe-runtime/values.yaml
```

2023-11-21 14:34 UTC, jhbertra requested changes
Looks good, just needs one change

2023-11-29 19:32 UTC, merged